### ISSUE TITLE
Configuration file not found when running subcommands

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1224]
### Context
When running some subcommands, it complains some configuration files can't be found:
```
./integritee-service mrenclave
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: configuration file "worker-config-dev.json" not found', service/src/main.rs:146:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

./integritee-service dump-ra
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: configuration file "worker-config-dev.json" not found', service/src/main.rs:146:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

We should give it a default config

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
My bad - I didn't have matching binary and enclave. After cleaning and re-compiling, it works
