### ISSUE TITLE
Some errors when running the sgx unit tests

### ISSUE THREAD

**Issue by ziming-zung** [litentry/litentry-parachain#1343]
### Context
I got some erros when running the sgx unit tests and the code based on the current dev branch. see:

> command: ./integritee-service test --all

```log
start running tests
testing itp_attestation_handler::attestation_handler::tests::decode_spid_works ... ok!
testing stf_sgx_tests::enclave_account_initialization_works ... ok!
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidMetadata', /root/work/tee-worker/app-libs/stf/src/stf_sgx_tests.rs:64:90
testing stf_sgx_tests::shield_funds_increments_signer_account_nonce ... failed!
testing stf_sgx_tests::test_root_account_exists_after_initialization ... ok!
testing itp_stf_state_handler::test::sgx_tests::test_write_and_load_state_works ... ok!
testing itp_stf_state_handler::test::sgx_tests::test_sgx_state_decode_encode_works ... ok!
testing itp_stf_state_handler::test::sgx_tests::test_encrypt_decrypt_state_type_works ... ok!
testing itp_stf_state_handler::test::sgx_tests::test_write_access_locks_read_until_finished ... ok!
testing itp_stf_state_handler::test::sgx_tests::test_ensure_subsequent_state_loads_have_same_hash ... ok!
testing itp_stf_state_handler::test::sgx_tests::test_state_handler_file_backend_is_initialized ... ok!
testing itp_stf_state_handler::test::sgx_tests::test_multiple_state_updates_create_snapshots_up_to_cache_size ... ok!
testing itp_stf_state_handler::test::sgx_tests::test_state_files_from_handler_can_be_loaded_again ... ok!
testing itp_stf_state_handler::test::sgx_tests::test_file_io_get_state_hash_works ... ok!
testing itp_stf_state_handler::test::sgx_tests::test_list_state_ids_ignores_files_not_matching_the_pattern ... ok!
testing itp_stf_state_handler::test::sgx_tests::test_in_memory_state_initializes_from_shard_directory ... ok!
testing test_compose_block ... ok!
testing test_submit_trusted_call_to_top_pool ... ok!
testing test_submit_trusted_getter_to_top_pool ... ok!
testing test_differentiate_getter_and_call_works ... ok!
testing test_create_block_and_confirmation_works ... ok!
testing test_create_state_diff ... ok!
testing test_executing_call_updates_account_nonce ... ok!
testing test_call_set_update_parentchain_block ... ok!
[2023-02-17T03:58:58Z ERROR itp_stf_executor::executor] Stf execute failed: InvalidNonce(10, 0)
testing test_invalid_nonce_call_is_not_executed ... ok!
[2023-02-17T03:58:58Z ERROR itp_stf_executor::executor] TrustedCallSigned: bad signature
testing test_signature_must_match_public_sender_in_call ... ok!
[2023-02-17T03:58:58Z ERROR ita_stf::helpers] Expected enclave account 9a47faa0dd2975294754aa01928fc0222d3fb0cf653f2fbff21876738bab3148, but found 2f8c6129d816cf51c374bc7f08c3e63ed156cf78aefb4a6550d97b87997977ee
[2023-02-17T03:58:58Z ERROR itp_stf_executor::executor] Stf execute failed: RequireEnclaveSignerAccount
testing test_non_root_shielding_call_is_not_executed ... ok!
testing test_shielding_call_with_enclave_self_is_executed ... ok!
testing test_retrieve_events ... ok!
testing test_retrieve_event_count ... ok!
testing test_reset_events ... ok!
testing rpc::worker_api_direct::tests::test_given_io_handler_methods_then_retrieve_all_names_as_string ... ok!
testing handle_state_mock::tests::initialized_shards_list_is_empty ... ok!
testing handle_state_mock::tests::shard_exists_after_inserting ... ok!
testing handle_state_mock::tests::from_shard_works ... ok!
testing handle_state_mock::tests::initialize_creates_default_state ... ok!
testing handle_state_mock::tests::load_mutate_and_write_works ... ok!
testing handle_state_mock::tests::ensure_subsequent_state_loads_have_same_hash ... ok!
testing handle_state_mock::tests::ensure_encode_and_encrypt_does_not_affect_state_hash ... ok!
testing test_verify_mra_cert_should_work ... ok!
[2023-02-17T03:58:58Z ERROR itp_attestation_handler::cert] Signature verification error InvalidSignatureForPublicKey
testing test_verify_wrong_cert_is_err ... ok!
[2023-02-17T03:58:58Z ERROR itp_attestation_handler::error] Returning error Other(Error("trailing characters", line: 1, column: 2)) as sgx unexpected.
testing test_given_wrong_platform_info_when_verifying_attestation_report_then_return_error ... ok!
testing sidechain_rw_lock_works ... ok!
testing enclave_rw_lock_works ... ok!
testing stf_executor_tests::propose_state_update_always_executes_preprocessing_step ... ok!
testing stf_executor_tests::propose_state_update_executes_no_trusted_calls_given_no_time ... ok!
testing stf_executor_tests::propose_state_update_executes_only_one_trusted_call_given_not_enough_time ... ok!
testing stf_executor_tests::propose_state_update_executes_all_calls_given_enough_time ... ok!
testing enclave_signer_tests::enclave_signer_signatures_are_valid ... ok!
testing enclave_signer_tests::derive_key_is_deterministic ... ok!
thread '<unnamed>' panicked at 'assertion failed: TestStf::execute_call(&mut state, &shard, trusted_call_1_signed,\n        &mut Vec::new(), repo).is_ok()', src/test/enclave_signer_tests.rs:131:5
testing enclave_signer_tests::nonce_is_computed_correctly ... failed!
testing state_getter_tests::state_getter_works ... ok!
[2023-02-17T03:58:58Z ERROR itp_stf_executor::executor] Stf execute failed: Dispatch("Balance Transfer error: Module(ModuleError { index: 2, error: [2, 0, 0, 0], message: Some(\"InsufficientBalance\") })")
testing sidechain_aura_tests::produce_sidechain_block_and_import_it ... ok!
[2023-02-17T03:58:59Z ERROR its_state::impls] Error decoding storage: System, Number. Error: Error { cause: None, desc: "Not enough data to fill buffer" }
testing sidechain_event_tests::ensure_events_get_reset_upon_block_proposal ... ok!
testing top_pool_tests::process_indirect_call_in_top_pool ... ok!
testing top_pool_tests::submit_shielding_call_to_top_pool ... ok!
testing tls_ra::seal_handler::test::seal_shielding_key_works ... ok!
[2023-02-17T03:58:59Z ERROR enclave_runtime::tls_ra::seal_handler]     [Enclave] Received Invalid RSA key
testing tls_ra::seal_handler::test::seal_shielding_key_fails_for_invalid_key ... ok!
testing tls_ra::seal_handler::test::unseal_seal_shielding_key_works ... ok!
testing tls_ra::seal_handler::test::seal_state_key_works ... ok!
testing tls_ra::seal_handler::test::seal_state_key_fails_for_invalid_key ... ok!
testing tls_ra::seal_handler::test::unseal_seal_state_key_works ... ok!
testing tls_ra::seal_handler::test::seal_state_works ... ok!
[2023-02-17T03:58:59Z ERROR itp_sgx_externalities::codec_impl] deserialization failed: DeserializeUnexpectedEnd
testing tls_ra::seal_handler::test::seal_state_fails_for_invalid_state ... ok!
testing tls_ra::seal_handler::test::unseal_seal_state_works ... ok!
    [Enclave] (MU-RA-Server) MU-RA successful sending keys
testing tls_ra::tests::test_tls_ra_server_client_networking ... ok!
    [Enclave] (MU-RA-Server) MU-RA successful sending keys
testing tls_ra::tests::test_state_and_key_provisioning ... ok!
testing direct_rpc_tests::get_state_request_works ... ok!
testing run_evm_tests ... ok!
testing run_teeracle_tests ... ok!

failures:
    stf_sgx_tests::shield_funds_increments_signer_account_nonce
    enclave_signer_tests::nonce_is_computed_correctly

test result FAILED. 69 tested, 67 passed, 2 failed
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Sgx(SGX_ERROR_INVALID_PARAMETER)', service/src/tests/mod.rs:39:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The `shield_funds_increments_signer_account_nonce` and `nonce_is_computed_correctly` always failed.

**Comment by zTgx** [comment]
Current dev branch commit hash `45c1cf6fcc97d1f9c1718d9f0a2ea6c162ea951b`
