### ISSUE TITLE
Error: The WASM interface has not been initialized

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1364]
### Context

Happened multiple times recently:

https://github.com/litentry/litentry-parachain/actions/runs/4247565225
https://github.com/litentry/litentry-parachain/actions/runs/4250721399

Before any ts-tests (so not ts-tests problem):
```
Trace: Error: Error: The WASM interface has not been initialized. Ensure that you wait for the initialization Promise with waitReady() from @polkadot/wasm-crypto (or cryptoWaitReady() from @polkadot/util-crypto) before attempting to use WASM-only interfaces.
    at /home/runner/work/litentry-parachain/litentry-parachain/docker/node_modules/@polkadot/wasm-crypto/cjs/bundle.js:46:13
    at sr25519PairFromSeed (/home/runner/work/litentry-parachain/litentry-parachain/docker/node_modules/@polkadot/util-crypto/cjs/sr25519/pair/fromSeed.js:22:82)
    at Object.sr25519 (/home/runner/work/litentry-parachain/litentry-parachain/docker/node_modules/@polkadot/keyring/cjs/keyring.js:19:56)
    at Keyring.createFromUri (/home/runner/work/litentry-parachain/litentry-parachain/docker/node_modules/@polkadot/keyring/cjs/keyring.js:256:115)
    at generateRelaychainGenesisFile (/home/runner/work/litentry-parachain/litentry-parachain/docker/node_modules/@open-web3/parachain-launch/lib/index.js:1[43](https://github.com/litentry/litentry-parachain/actions/runs/4250721399/jobs/7393584955#step:8:44):31)
    at generate (/home/runner/work/litentry-parachain/litentry-parachain/docker/node_modules/@open-web3/parachain-launch/lib/index.js:374:5)
    at fatal (/home/runner/work/litentry-parachain/litentry-parachain/docker/node_modules/@open-web3/parachain-launch/lib/index.js:55:13)
make: *** [Makefile:175: generate-docker-compose-rococo] Error 1
```

Is it a parachain-launch problem? We use [parachain-launch](https://github.com/open-web3-stack/parachain-launch) to start the local parachain network with docker.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
Haven't found a reason. Stack trace:
```
at /home/runner/work/litentry-parachain/litentry-parachain/docker/node_modules/@polkadot/wasm-crypto/cjs/bundle.js:46:13
    at sr25519PairFromSeed (/home/runner/work/litentry-parachain/litentry-parachain/docker/node_modules/@polkadot/util-crypto/cjs/sr25519/pair/fromSeed.js:22:82)
    at Object.sr25519 (/home/runner/work/litentry-parachain/litentry-parachain/docker/node_modules/@polkadot/keyring/cjs/keyring.js:19:56)
    at Keyring.createFromUri (/home/runner/work/litentry-parachain/litentry-parachain/docker/node_modules/@polkadot/keyring/cjs/keyring.js:256:115)
    at generateRelaychainGenesisFile (/home/runner/work/litentry-parachain/litentry-parachain/docker/node_modules/@open-web3/parachain-launch/lib/index.js:1[43](https://github.com/litentry/litentry-parachain/actions/runs/4247565225/jobs/7386926356#step:8:44):31)
    at generate (/home/runner/work/litentry-parachain/litentry-parachain/docker/node_modules/@open-web3/parachain-launch/lib/index.js:374:5)
    at fatal (/home/runner/work/litentry-parachain/litentry-parachain/docker/node_modules/@open-web3/parachain-launch/lib/index.js:55:13)
```

However in `generate()` we do have `await cryptoWaitReady();` at the beginning, version issue?
